name: Govee api check 

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0/15 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    concurrency: 'only_one_scraper'

    steps:
    - name: mask secrets in logs
      run: |
        echo "::add-mask::${{ secrets.LOG_MASKS }}"
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: test connectivity
      env:
        GOVEE_API_KEY: ${{ secrets.GOVEE_API_KEY }}
      run: |-
        python govee_api_up.py
    - name: Create plots
      run: |-
        python govee_api_up_plot.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git pull
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
