name: scrape and plot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12 ]
    
    concurrency: 'only_one_scraper'

    steps:
    - name: mask secrets in logs
      run: |
        echo "::add-mask::${{ secrets.LOG_MASKS }}"
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch latest data
      run: |-
        scrapy runspider goveestats_installations.py -o output/goveestats_installations.jsonl -t jsonlines
    - name: Create plots
      run: |-
        python goveestats_installations_plot.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git pull
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
